FROM centos:6.8
MAINTAINER Yauhen Mihura (yauhen_mihura@epam.com)

RUN useradd -d "/var/jenkins_home" -u 1000 -m -s /bin/bash jenkins
RUN mkdir -p /var/jenkins_home/plugins
RUN chown -R jenkins:jenkins /var/jenkins_home/plugins

VOLUME [ "/var/jenkins_home/plugins"  ]
USER jenkins

CMD [ "echo", "Data plugins container for Jenkins" ]
